FROM python:3.9

WORKDIR /usr/src/app/

RUN pip install -U pip
RUN pip install --no-cache-dir chromadb
RUN pip install --no-cache-dir langchain_community
RUN pip install --no-cache-dir langchain_text_splitters
RUN pip install --no-cache-dir sentence-transformers
RUN pip install --no-cache-dir openai
RUN pip install --no-cache-dir flask
RUN pip install --no-cache-dir ollama

COPY ./rag_query.py .
COPY ./frontend_init.sh .

EXPOSE 80

RUN chmod +x ./rag_query.py
RUN chmod +x ./frontend_init.sh

ENV FLASK_APP=rag_query.py
ENV FLASK_RUN_PORT=80

CMD ["./frontend_init.sh"]
