FROM python:3.9

WORKDIR /usr/src/app/

RUN pip install -U pip
RUN pip install --no-cache-dir chromadb
RUN pip install --no-cache-dir langchain_community
RUN pip install --no-cache-dir sentence-transformers
RUN pip install --no-cache-dir flask
RUN pip install --no-cache-dir ollama

COPY ./frontend.py .

RUN chmod +x ./frontend.py

ENV FLASK_APP=frontend.py
ENV FLASK_RUN_PORT=80

EXPOSE 80

CMD ["flask", "run", "--host=0.0.0.0"]
