services:
    frontend:
        image: frontend
        ports:
            - 8080:80
        stdin_open: true
        deploy:
            mode: global
            placement:
                constraints:
                    - node.hostname == frontend-chroma-vm
        networks:
            - rag-overlay-internal-net
            - rag-bridge-net
networks:
    rag-overlay-internal-net:
        name: rag-overlay-internal-net
        external: true
    rag-bridge-net:
        name: rag-bridge-net
        external: true
