FROM python:3.9

WORKDIR /usr/src/app

RUN pip install -U pip
RUN pip install --no-cache-dir chromadb
RUN pip install --no-cache-dir langchain_community
RUN pip install --no-cache-dir langchain_text_splitters
RUN pip install --no-cache-dir sentence-transformers
RUN pip install --no-cache-dir openai
RUN pip install --no-cache-dir flask
RUN pip install --no-cache-dir ollama
RUN pip install --no-cache-dir unstructured
RUN pip install --no-cache-dir "unstructured[pdf]"
RUN pip install --no-cache-dir pymupdf

COPY ./documents/ ./documents/
COPY ./rag.py .
COPY ./rag_query.py .
COPY ./rag_init.sh .

EXPOSE 80

ENV FLASK_APP=rag_query.py
ENV FLASK_RUN_PORT=80

RUN chmod +x ./rag_init.sh

CMD ["./rag_init.sh"]
