services:

  ollama:
    image: ollama-gguf
    build:
      context: .
      dockerfile: ./Dockerfile.ollama
    hostname: ollama
    ports:
      - 11434:11434   # port 11434 of the host is mapped to port 11434 of the container
    healthcheck: 
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag-backend-net
    entrypoint: ["/usr/bin/bash", "./ollama_init.sh"]
    stdin_open: true
    deploy:
      mode: global
      placement:
        constraints:
        - node.hostname == ollama-vm
  
  chroma:
    image: chromadb/chroma
    hostname: chroma
    ports:
      - 8000:8000   # port 8000 of the host is mapped to port 8000 of the container
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/8000'"
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag-backend-net
    stdin_open: true
    deploy:
      mode: global
      placement:
        constraints:
        - node.hostname == frontend-chroma-vm

networks:
  rag-backend-net:
    name: rag-backend-net
    external: true
