services:

    ollama:
        image: ollama-gguf:1.1
        entrypoint: ["/usr/bin/bash", "./ollama_init.sh"]
        deploy:
            mode: global
            placement:
                constraints:
                    - node.hostname == ollama-vm
        stdin_open: true
        networks:
            - rag-overlay-internal-net
  
    chroma:
        image: chromadb/chroma    
        deploy:
            mode: global
            placement:
                constraints:
                    - node.hostname == frontend-chroma-vm
        networks:
            - rag-overlay-internal-net

networks:
    rag-overlay-internal-net:
        name: rag-overlay-internal-net
        external: true
