services:

  dbinit:
    image: dbinit
    build:
      context: .
      dockerfile: ./Dockerfile.dbinit
    networks:
      - rag-overlay-internal-net
      - rag-bridge-net
    restart: on-failure
    deploy:
      mode: global
      placement:
        constraints:
        - node.hostname == frontend-chroma-vm

networks:
  rag-overlay-internal-net:
      name: rag-overlay-internal-net
      external: true
  rag-bridge-net:
    name: rag-bridge-net
    external: true
