services:
    dbinit:
        image: dbinit
        deploy:
            mode: global
            placement:
                constraints:
                    - node.hostname == frontend-chroma-vm
        restart: on-failure
        networks:
            - rag-overlay-internal-net
            - rag-bridge-net
networks:
    rag-overlay-internal-net:
        name: rag-overlay-internal-net
        external: true
    rag-bridge-net:
        name: rag-bridge-net
        external: true
